using AirportCEOTweaksCore.lib;
using BepInEx.Configuration;
using System;
using System.Collections.Generic;

namespace AirportCEONationality
{
    public class AirportCEONationalityConfig
    {
        internal static ConfigEntry<bool> EnableNationalityFlightGeneration { get; private set; }
        internal static ConfigEntry<float> VintageGenerationMultiplier { get; private set; }
        internal static ConfigEntry<float> InternationalGenerationMultiplier { get; private set; }
        internal static ConfigEntry<bool> ExtraDebugLogs{ get; private set; }
        internal static ConfigEntry<NationalityFallbackRule> FallbackGenerationMode { get; private set; }
        internal static ConfigEntry<bool> IgnoreRangeLimitsFirst { get; private set; }
        internal static ConfigEntry<bool> ShowWarningWhenFallingBack { get; private set; }

        internal static void SetUpConfig()
        {
            

            EnableNationalityFlightGeneration = ConfigRef.Bind("General", "Enable Nationality Flight Generation", true, new ConfigDescription("Switch flight generation to nationality flight generation?", null, new ConfigurationManagerAttributes { Order = 100 } ));

            VintageGenerationMultiplier = ConfigRef.Bind("Flight Generation Tweaks", "Vintage Generation Multiplier", 0.5f, new ConfigDescription("Reduce (or increase) the chance of vintage planes generating", 
                new AcceptableValueRange<float>(0, 2f)));
            InternationalGenerationMultiplier = ConfigRef.Bind("Flight Generation Tweaks", "International Generation Multiplier", 0.5f, new ConfigDescription("Reduce (or increase) the chance of international " +
                "flights generating. Ex: 0.5 to halve the chance of international flights generating compared to domestic", new AcceptableValueRange<float>(0, 2f)));

            FallbackGenerationMode = ConfigRef.Bind("General", "Fallback Generation Mode", NationalityFallbackRule.FallbackVanilla, "What to do if the mod is unable to generate flights " +
                "using the realistic nationality generation system. Fallback to vanilla is recommended");
            EnableNationalityFlightGeneration.SettingChanged += NationalityFlightGenerator.ToggleGenerator;
            ShowWarningWhenFallingBack = ConfigRef.Bind("General", "Show Warning When Falling Back", true, "Show a warning message when the mod has to fall back to the selected fallback option? " +
                "This is recommended to be on so you understand why things are generating as they are.");
            IgnoreRangeLimitsFirst = ConfigRef.Bind("General", "Ignore Range Limits Before Falling Back", true, "Should the mod try ignoring range limits before falling back to the selected fallback option? " +
                "This can result in more flights being generated by the mod, but can also result in unrealistic flights generating. This is recommended to be on.");

            ExtraDebugLogs = ConfigRef.Bind("Debug", "Extra Debug Logs", false, new ConfigDescription("Logs lots of extra info about flights generating.", null, new ConfigurationManagerAttributes { IsAdvanced = true } ));
        }

        private static ConfigFile ConfigRef => AirportCEONationality.ConfigReference;
    }
}